manage_hr/manage_hr/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('manage_hr_app/', include('manage_hr_app.urls')),
]

manage_hr/manage_hr_app/urls.py
from django.urls import path
from . import views

app_name = "manage_hr_app"


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
]

manage_hr/manage_hr_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Student(models.Model):
    first_name = models.CharField("student's first name", max_length = 256)
    last_name = models.CharField("student's last name", max_length = 256)
    email = models.EmailField("email address", max_length = 256, unique = True)
    phone = models.SmallIntegerField(unique = True) # ハイフンは含まないで入力ように設定
    password = models.CharField("password", max_length = 512)
    school_id = models.PositiveSmallIntegerField()
    grade = models.PositiveSmallIntegerField(unique = True)
    age = models.PositiveSmallIntegerField(null = False)
    bday = models.DateField(null = True)
    chara = models.TextField(null = True)
    flag = models.BooleanField(null = False, default = True) # 塾に所属しているか否か
    created_date = models.DateTimeField(auto_now=False, auto_now_add=True, editable=False)
    # created_date = models.DateTimeField(False, True, editable=False, default=datetime.now()) だとエラーになる
    def __str__(self):
        return "User name is {} {}.".format(self.first_name, self.last_name)
    


class Friend(models.Model):
    # student_id = models.SmallIntegerField(unique = True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null = False, related_name='%(class)s_student')
    # friend_id = models.SmallIntegerField(unique = True)
    friend = models.ForeignKey(Student, on_delete=models.CASCADE, null = False, related_name='%(class)s_friend')
    
    def __str__(self):
        return "{}".format(self.student)

class BelongSchool(models.Model):
    school_name = models.CharField(max_length = 256, null = False)
    department = models.CharField(max_length = 256, null = True)
    concentration = models.CharField(max_length = 256, null = True)
    My_choices = (
        ("A", "Art"),
        ("S", "Science"),
    )
    art_or_science = models.CharField(max_length = 1, choices= My_choices)
    deviation = models.PositiveSmallIntegerField(null = True, validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ])

    def __str__(self):
        return "{}".format(self.school_name)


class DesiredSchool(models.Model):
    # student_id = models.SmallIntegerField(unique = True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null = False)
    # school_id = models.SmallIntegerField(unique = True)
    school = models.ForeignKey(BelongSchool, on_delete=models.CASCADE, null = False)
    
    def __str__(self):
        return "{}".format(self.student)

    

manage_hr/manage_hr_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views import generic
from .models import Student
from django.db.models import Q

# Create your views here.

class IndexView(generic.ListView):
    model = Student
    paginate_by = 10

    """
    def get_queryset(self):
        queryset = Student.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(text__icontains=keyword)
            )
        return queryset
    """

class DetailView(generic.DetailView):
    model = Student

manage_hr/manage_hr_app/templates/manage_hr_app/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>ブログ</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">ブログ</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
           
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'blog:index' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="jumbotron">
      <h1 class="display-3">ブログタイトル!</h1>
      <p class="lead">○○に関するブログです</p>
      <hr class="my-2">
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}
          {% endblock %}
        </div>
        <div class="col-md-4">
          <ul class="list-group">
            <li class="list-group-item bg-dark text-white">カテゴリ一覧</li>
            {% for category in category_list %}
              <li class="list-group-item"><a href="{% url 'blog:category' category.pk %}">{{ category }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>

    <footer class="bg-dark text-white text-center py-3">
      <p>あなたの名前</p>  
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

manage_hr/manage_hr_app/templates/manage_hr_app/student_detail.html
{%load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static "table.css" %}">
</head>
<title>生徒情報</title>

{% block content %}
<table>
	<tr>
	    <td>ID</td>
	    <td>名前</td>
	    <td>苗字</td>
	    <td>メール</td>
	    <td>電話</td>
	    <td>パスワード</td>
	    <td>学校</td>
	    <td>学年</td>
	    <td>年齢</td>
	    <td>誕生日</td>
	    <td>性格</td>
	    <td>所属してるか否か</td>
	    <td>作成日</td>
	  </tr>
	<tr>
		<td>{{ student.id }}</td>
		<td>{{ student.first_name }}</td>
		<td>{{ student.last_name }}</td>
		<td>{{ student.email }}</td>
		<td>{{ student.phone }}</td>
		<td>{{ student.password }}</td>
		<td>{{ student.school_id }}</td>
		<td>{{ student.grade }}</td>
		<td>{{ student.age }}</td>
		<td>{{ student.bday }}</td>
		<td>{{ student.chara }}</td>
		<td>{{ student.flag }}</td>
		<td><time>{{ student.created_date|date:"M j, Y H:i:s" }}</time></td>
		<!-- dateの参照:
             https://dot-blog.jp/news/django-template-date/ -->
	</tr>
</table>

<a href = "{% url 'manage_hr_app:index' %}">戻る</a>
{% endblock %}

manage_hr/manage_hr_app/templates/manage_hr_app/student_list.html
{%load static %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static "table.css" %}">
</head>

{% block content %}
<table>
  <tr>
    <td>ナンバー</td>
    <td>ID</td>
    <td>名前</td>
    <td>苗字</td>
  </tr>

  {% for student in student_list %}
    <div class="card mb-3">
      <h2 class="card-header bg-dark text-white"></h2>
      <div class="card-body">
        <tr>
            <td>{{ forloop.counter }}</td>
          <td><a href = "{% url 'manage_hr_app:detail' student.id %}">{{ student.id }}</a></td>
          <td>{{ student.first_name }}</td>
          <td>{{ student.last_name }}</td>
        </tr> 
      </div>
    </div>
  {% endfor %}
</table>

{% endblock %}

<!--テーブルに対するスタイルシート-->